### ISSUE TITLE
Cannot read property 'ownerDocument' of null

### ISSUE THREAD

**Issue by willwhitney** [nteract/jupyter-display-area#20]
Requiring this package in an Atom context results in this error:

```
TypeError: Cannot read property 'ownerDocument' of null
    at /Users/will/code/jupyter-notebook-atom/node_modules/jupyter-display-area/dist/jupyter-display-area.js:137:68
    at Object.2../custom-renderers (/Users/will/code/jupyter-notebook-atom/node_modules/jupyter-display-area/dist/jupyter-display-area.js:336:3)
    at s (/Users/will/code/jupyter-notebook-atom/node_modules/jupyter-display-area/dist/jupyter-display-area.js:1:316)
    at e (/Users/will/code/jupyter-notebook-atom/node_modules/jupyter-display-area/dist/jupyter-display-area.js:1:487)
    at Object.<anonymous> (/Users/will/code/jupyter-notebook-atom/node_modules/jupyter-display-area/dist/jupyter-display-area.js:1:505)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/will/code/jupyter-notebook-atom/lib/notebook-cell.js:24:22)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:166:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/will/code/jupyter-notebook-atom/lib/notebook-editor-view.js:22:182)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:166:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/will/code/jupyter-notebook-atom/lib/notebook-editor.js:17:94)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:166:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/will/code/jupyter-notebook-atom/lib/main.js:13:22)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:166:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:709:34)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:188:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:179:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:372:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:336:14)
    at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:642:21)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:96:23)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:36:7)
```

**Comment by willwhitney** [comment]
`document.currentScript` seems to always be `null` in Atom

**Comment by rgbkrk** [comment]
I wonder if that's because Atom is node first always.

We need to break most of this out and away from web components, we don't even need them necessarily since our templates are so light.
